logo: "/images/darapheaktin.png?raw=true" # your photo (or logo) here
title: Darapheak Tin # your name (or website title) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br>
  PhD Candidate <br>
  Research School of Economics <br>
  The Australian National University <br> 
  HW Arndt Building 25A, Kingsley Pl <br> 
  Acton ACT 2601 
  <br><br><br>
  Welcome to my personal site! <br> 
  It is still under construction at the moment. <br> 
  Please be patient. 
  <br><br>
  <b>Email</b>: <a href="darapheak.tin@anu.edu.au">darapheak.tin@anu.edu.au</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-213732110-1 # your Google Analytics tracking ID here
