baseURL: "https://darapheaktin.github.io/"
title: Darapheak Tin
pagination:
  pagerSize: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: /research/
      weight: 1
    - name: Teaching
      url: /teaching/
      weight: 2
    - name: Other
      url: /other/
    # - name: Teaching
    #   url: /teaching/
    #   weight: 4
    # - name: Archive
    #   url: /archive/
    #   weight: 5

params:
  customCSS: ["css/custom.css"]
  description: "I am an economist researching at the crossroads of Public Finance, Labor Economics, Macroeconomics, and Computational Economics, integrating these fields to tackle complex economic questions. I am currently on the 2024-25 academic job market. 

My research explores the aggregate, distributional, and behavioral impacts of fiscal policies through micro-founded macroeconomic models grounded in strong empirical foundations. With a blend of single and collaborative projects, I aim to contribute meaningful insights to pressing economic questions. In addition to my research, I bring extensive teaching experience with high performance ratings since 2018."
  author: Darapheak Tin
  googleAnalyticsID: "UA-213732110-1"
  DateFormat: "November 2024"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Darapheak Tin
    subtitle: "I am an economist researching at the crossroads of Public Finance, Labor Economics, Macroeconomics, and Computational Economics, integrating these fields to tackle complex economic questions. I am currently on the 2024-25 academic job market. 

     <br><br>
My research explores the aggregate, distributional, and behavioral impacts of fiscal policies through micro-founded macroeconomic models grounded in strong empirical foundations. With a blend of single and collaborative projects, I aim to contribute meaningful insights to pressing economic questions. In addition to my research, I bring extensive teaching experience with high performance ratings since 2018.

     <br> <br>

     Thank you for visiting my webpage.
     <br> <br>
     I am rebuilding the webpage and will get it up and running soon.
     "
    imageUrl: "/darapheaktin_photo.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Darapheak Tin
    buttons:
      - name: Research
        url: /research/
      - name: Teaching
        url: /teaching/
      - name: Other
        url: /other/
      # - name: News
      #   url: /news/

  social:
    - name: CV
      url: "/DarapheakTin_CV.pdf"
    # - name: LinkedIn
    #   url: "https://www.linkedin.com/in/samia-kabir/"
    # - name: Google Scholar
    #   url: "https://scholar.google.com/citations?user=DZ5jg-IAAAAJ&hl=en"
    # - name: GitHub
    #   url: "https://github.com/SamiaKabir"
    - name: Email
      url: "mailto:darapheak.tin@anu.edu.au"

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Darapheak Tin"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: xcode
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
