baseURL: "https://darapheaktin.github.io/"
title: Darapheak Tin
pagination:
  pagerSize: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: CV and Statements
      url: /cvstatements/
      weight: 1
    - name: Research
      url: /research/
      weight: 2
    - name: Teaching
      url: /teaching/
      weight: 3
    - name: Other
      url: /other/
      weight: 4
    - name: Contact 
      url: /contact/
      weight: 5

params:
  description: "I am an economist researching at the crossroads of Public Finance, Labor Economics, Macroeconomics, and Computational Economics, integrating these fields to tackle complex economic questions. I am currently on the 2024-25 academic job market. 
  My research explores the aggregate, distributional, and behavioral impacts of fiscal policies through micro-founded macroeconomic models grounded in strong empirical foundations. With a blend of single and collaborative projects, I aim to contribute meaningful insights to pressing economic questions. In addition to my research, I bring extensive teaching experience with high performance ratings since 2018."
  author: Darapheak Tin
  googleAnalyticsID: "UA-213732110-1"
  DateFormat: "November 2024"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Darapheak Tin
    subtitle: |
      I am an economist researching at the crossroads of Public Finance, Labor Economics, Macroeconomics, and Computational Economics. I am currently on the 2024-25 academic job market.

      <br>

      <b>Research</b>: By modeling behavioral responses in a general equilibrium framework with rich household heterogeneity, my research explores the aggregate and distributional impacts of tax and transfer policies, focusing on their unintended consequences on the intended beneficiaries. With a blend of empirical and quantitative projects, my work contributes to the understanding of optimal public policy design. I am also interested in extending my framework to study policies in developing countries and explore economic and social phenomena beyond policy analysis. 
  
      <br>
       
      <b>Teaching</b>: I also bring extensive teaching experience across a diverse range of courses, including Microeconomics, Macroeconomics, Public Economics, International Economics, and Mathematics, consistently achieving high performance ratings since 2018, with an average over 4.5/5.

      <br>

      Thank you for visiting my website. 

      <br>

    imageUrl: "/darapheaktin_photo.png"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Darapheak Tin
    buttons:
      - name: CV and Statements
        url: /cvstatements/
      - name: Research
        url: /research/
      - name: Teaching
        url: /teaching/
      - name: Other
        url: /other/
      - name: Contact
        url: /contact/

  social:
    - name: CV
      url: "/DarapheakTin_CV.pdf"
    - name: Email
      url: "mailto:darapheak.tin@anu.edu.au"

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Darapheak Tin"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: xcode
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
